// Posts feed
export const FETCH_POSTS_INIT = 'FETCH_POSTS_INIT'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR'

// Individual post
export const FETCH_POST_INIT = 'FETCH_POST_INIT'
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS'
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR'
